
sensors:
  - my_pointcloud
my_pointcloud:
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  point_cloud_topic: /zed_pointcloud
  max_range: 1.5
  point_subsample: 1
  padding_offset: 0.1
  padding_scale: 1.15
  max_update_rate: 0.0
  octomap_resolution: 0.02
  filtered_cloud_topic: /zed_pointcloud_filtered
  transform_tolerance:  0.1
octomap_resolution: 0.02
  