ARG ISAAC_VERSION="5.1.0"
# expects context to be the root of the repository, i.e. AutoLab/. this is so we can access AutoLab/ros_ws/
FROM nvcr.io/nvidia/isaac-sim:${ISAAC_VERSION}
ARG ISAAC_VERSION
WORKDIR /isaac-sim

# isaac's ros2 launch run_isaacsim.launch.py hardcodes to search in this path, so we have to put the executables here
USER root
RUN mkdir -p /root/.local/share/ov/pkg/ && \
    ln -s /isaac-sim /root/.local/share/ov/pkg/isaac-sim-${ISAAC_VERSION}

# allows us to run isaac-sim as root
ENV OMNI_KIT_ALLOW_ROOT=1

# setup environment
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV ROS_DISTRO=jazzy

# setup timezone
RUN echo 'Etc/UTC' > /etc/timezone && \
    ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime && \
    apt-get update && \
    apt-get install -q -y --no-install-recommends tzdata && \
    rm -rf /var/lib/apt/lists/*

# install base packages
RUN apt-get update && apt-get install -q -y --no-install-recommends \
    dirmngr \
    gnupg2 \
    unzip \
    tmux \
    iputils-ping \
    net-tools \
    curl \
    emacs \
    vim \
    nano \
    gdb \
    xterm \
    tree \
    less \
    htop \
    jq \
    git \
    build-essential \
    cmake \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    meson \
    ninja-build \
    wget \
    libcgal-dev && \
    rm -rf /var/lib/apt/lists/*

# setup ros2 key
RUN set -eux; \
    key='C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654'; \
    export GNUPGHOME="$(mktemp -d)"; \
    gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "$key"; \
    mkdir -p /usr/share/keyrings; \
    gpg --batch --export "$key" > /usr/share/keyrings/ros2-latest-archive-keyring.gpg; \
    gpgconf --kill all; \
    rm -rf "$GNUPGHOME"

# setup ros2 apt source
RUN echo "deb [ signed-by=/usr/share/keyrings/ros2-latest-archive-keyring.gpg ] http://packages.ros.org/ros2/ubuntu noble main" > /etc/apt/sources.list.d/ros2-latest.list

# Remove conflicting third-party apt sources that cause libbrotli conflicts
RUN rm -f /etc/apt/sources.list.d/*deb.sury.org*.list || true && apt-get update

RUN apt-get update && \
    # apt-get install -y --allow-downgrades --no-install-recommends libbrotli1=1.0.9-2build6 && \
    # apt-mark hold libbrotli1 && \
    apt-get install -y --no-install-recommends \
    libfreetype6-dev \
    libfontconfig1-dev \
    ros-jazzy-desktop \
    ros-dev-tools \
    python3-rosdep \
    ros-jazzy-tf2* \
    ros-jazzy-ackermann-msgs \
    ros-jazzy-topic-tools \
    ros-jazzy-grid-map \
    ros-jazzy-domain-bridge \
    ros-jazzy-moveit \
    python3-colcon-common-extensions && \
    rm -rf /var/lib/apt/lists/*

# install python packages
RUN /isaac-sim/python.sh -m pip install --upgrade pip && \
    /isaac-sim/python.sh -m pip install PyYAML tmuxp scipy \
    kconfiglib jinja2 empy==3.3.4 jsonschema pyros-genmsg packaging toml numpy future
# RUN /isaac-sim/python.sh -m pip install git+https://github.com/dronekit/dronekit-python#egg=dronekit && \
#     pip install PyYAML mavproxy tmuxp scipy \
#     kconfiglib jinja2 empy==3.3.4 jsonschema pyros-genmsg packaging toml numpy future

ARG isaac_dir_name="IsaacSim-ros_workspaces-IsaacSim-${ISAAC_VERSION}"
# Install Isaac Sim ROS2 workspace so that we can run the isaacsim ROS package
RUN cd /tmp/ && \
    curl -L -O https://github.com/isaac-sim/IsaacSim-ros_workspaces/archive/refs/tags/IsaacSim-${ISAAC_VERSION}.zip && \
    unzip IsaacSim-${ISAAC_VERSION}.zip && \
    mv ${isaac_dir_name}/jazzy_ws /jazzy_ws && \
    cd /jazzy_ws && \
    . /opt/ros/jazzy/setup.sh && \
    colcon build --symlink-install && \
    rm -rf /tmp/IsaacSim-${ISAAC_VERSION}.zip /tmp/${isaac_dir_name}

# TODO: Hacky way to make sure the Isaac Sim app is installed.
# PegasusSimulator extension requires this file to exist
# This is a workaround until we find a better way to ensure the app is installed
RUN mkdir -p /isaac-sim/apps && \
    touch /isaac-sim/apps/isaacsim.exp.base.kit

# "Install" PegasusSimulator extension. This installs in editable mode; when we run the container we mount the PegasusSimulator repo
# over the same directory so that we can edit the code and have it reflected in the container.
WORKDIR /root/Documents/Kit/shared/exts/

# rm -rf /tmp/PegasusSimulator
ENV ISAACSIM_PATH=/isaac-sim
ENV ACCEPT_EULA="Y"
# ENV ISAACSIM_PYTHON=/isaac-sim/python.sh


RUN /isaac-sim/python.sh -m pip install lark-parser

# TMux config
RUN git clone https://github.com/tmux-plugins/tpm /root/.tmux/plugins/tpm

# copy FastDDS config
COPY docker/fastdds.xml /isaac-sim/fastdds.xml

# ROS2 jazzy launch script seeks this
RUN ln -s /isaac-sim /root/isaacsim

# Cleanup. Prevent people accidentally doing git commits as root in Docker
RUN apt purge -y git && apt autoremove -y \
    && apt clean -y \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /isaac-sim