# Sourced by the robot and gcs .bashrc files.
#
# Real hardware (robot-l4t / gcs-real) runs with network_mode: host, so Fast DDS advertises every
# host interface - including Docker bridge IPs like 172.17.0.1 that exist identically on every
# machine. A remote peer sees one of its own addresses in that list, treats us as local, and sends
# its discovery replies to itself: discovery silently fails in both directions.
#
# When DDS_LAN_SUBNET is set (e.g. "192.168.10." - keep the trailing dot so it can't also match
# 192.168.100.x), generate a profile that restricts Fast DDS to this host's IP on that subnet plus
# loopback, and point FASTRTPS_DEFAULT_PROFILES_FILE at it. Unset (simulation): no-op.

if [ -n "${DDS_LAN_SUBNET:-}" ]; then
    _dds_lan_ip=""
    for _dds_ip in $(hostname -I 2>/dev/null); do
        case "$_dds_ip" in
            "$DDS_LAN_SUBNET"*) _dds_lan_ip="$_dds_ip"; break ;;
        esac
    done

    if [ -z "$_dds_lan_ip" ]; then
        echo "WARNING: DDS_LAN_SUBNET='$DDS_LAN_SUBNET' matches no local IPv4 ($(hostname -I 2>/dev/null))." \
             "Keeping FASTRTPS_DEFAULT_PROFILES_FILE=$FASTRTPS_DEFAULT_PROFILES_FILE - cross-machine ROS will not work." >&2
    else
        _dds_profile="$HOME/.ros/fastdds_lan.xml"
        mkdir -p "$HOME/.ros"
        # write-then-rename: several shells (tmux autolaunch, interactive) may source this at once
        cat > "$_dds_profile.$$" <<EOF
<?xml version="1.0" encoding="UTF-8" ?>
<!-- Generated by common/dds_lan_profile.sh - do not edit. -->
<profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
  <transport_descriptors>
    <transport_descriptor>
      <transport_id>udp_lan</transport_id>
      <type>UDPv4</type>
      <interfaceWhiteList>
        <address>$_dds_lan_ip</address>
        <address>127.0.0.1</address>
      </interfaceWhiteList>
    </transport_descriptor>
  </transport_descriptors>
  <participant profile_name="udp_lan_profile" is_default_profile="true">
    <rtps>
      <userTransports>
        <transport_id>udp_lan</transport_id>
      </userTransports>
      <useBuiltinTransports>false</useBuiltinTransports>
    </rtps>
  </participant>
</profiles>
EOF
        mv -f "$_dds_profile.$$" "$_dds_profile"
        export FASTRTPS_DEFAULT_PROFILES_FILE="$_dds_profile"
    fi
    unset _dds_lan_ip _dds_ip _dds_profile
fi
