lab_machine_executive:
  ros__parameters:
    ot2_base_url: "http://192.168.1.100:8000"
    ot2_host: "192.168.1.100"
    shaker_base_url: "http://shaker.autolab"
    shaker_endpoint: "/pwm_control/"
