# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    demo_bot_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    demo_bot_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

demo_bot_arm_controller:
  ros__parameters:
    joints:
      - Revolute_10
      - Revolute_11
      - Revolute_12
      - Revolute_13
      - Revolute_14
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
demo_bot_gripper_controller:
  ros__parameters:
    joints:
      - Slider_1
      - Slider_2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity